openapi: 3.0.0
info:
  title: Shopping app
  description: learning api and backend
  version: 1.0.0


# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: local host url
#   - url: "https://localhost:4000/api/v1"
#     description: dummy url

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: local host url
    variables:
      protocol: 
        enum:
          - http
          - https
        default: http
      version:
        enum:
          - v1
          - v2
        default: v1

components:
  securitySchemes:
    cookieAuth: 
      name: token
      type: apiKey
      in: cookie
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /:
    get:
      description: home page
      responses:
        200:
          description: Home page
          content:
            application/json:
              schema:
                type: string
  /signup:
    post:
      description: signup
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                name: 
                 type: string
                email:
                  type: string
                password:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        200:
          description: Sign up success
        400:
          description: Bad request
        500:
          description: Internal server error
  /login:
    post:
      description: login
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login up success
        400:
          description: Bad request
        500:
          description: Internal server error
  /logout:
    get:
      description: logout
      responses:
        200:
          description: Logout up success
        400:
          description: Bad request
        500:
          description: Internal server error
  




